# file: roles/openshift.config/tasks/logging.yml
---

- name: Add metricsPublicURL to master-config file
  become: yes
  lineinfile:
    dest: /etc/origin/master/master-config.yaml
    insertafter: "assetConfig:"
    line:  "  loggingPublicURL: https://kibana.apps.ocp.{{ domain_name }}"

- name: Restart master service
  become: yes
  service:
    name: atomic-openshift-master.service
    state: restarted
